### DISCUSSION TITLE
Cloudformation template?

### DISCUSSION THREAD

**Discussion by playitcool** [typedorm/typedorm#278] [Q&A]
Is there one available as an example or starting point for single table? I think have a schema that works but wanted to make sure I'm not doing anything weird. 

```json
{
  "Type": "AWS::DynamoDB::Table",
  "Properties": {
    "BillingMode": "PAY_PER_REQUEST",
    "TableName": "table-of-doom",
    "KeySchema": [
      { "AttributeName": "pk", "KeyType": "HASH" },
      { "AttributeName": "sk", "KeyType": "RANGE" }
    ],
    "AttributeDefinitions": [
      { "AttributeName": "pk", "AttributeType": "S" },
      { "AttributeName": "sk", "AttributeType": "S" },
      { "AttributeName": "gsi1_sk", "AttributeType": "S" },
      { "AttributeName": "gsi2_sk", "AttributeType": "S" },
      { "AttributeName": "lsi1_sk", "AttributeType": "S" }
    ],
    "GlobalSecondaryIndexes": [
      {
        "IndexName": "gsi1",
        "Projection": { "ProjectionType": "ALL" },
        "KeySchema": [
          { "AttributeName": "pk", "KeyType": "HASH" },
          { "AttributeName": "gsi1_sk", "KeyType": "RANGE" }
        ]
      },
      {
        "IndexName": "gsi2",
        "Projection": { "ProjectionType": "ALL" },
        "KeySchema": [
          { "AttributeName": "sk", "KeyType": "HASH" },
          { "AttributeName": "gsi2_sk", "KeyType": "RANGE" }
        ]
      },
      {
        "IndexName": "gsi3",
        "Projection": { "ProjectionType": "ALL" },
        "KeySchema": [
          { "AttributeName": "gsi1_sk", "KeyType": "HASH" },
          { "AttributeName": "pk", "KeyType": "RANGE" }
        ]
      }
    ],
    "LocalSecondaryIndexes": [
      {
        "IndexName": "lsi1",
        "Projection": { "ProjectionType": "KEYS_ONLY" },
        "KeySchema": [
          { "AttributeName": "pk", "KeyType": "HASH" },
          { "AttributeName": "lsi1_sk", "KeyType": "RANGE" }
        ]
      }
    ]
  }
}
```
TIA

**Comment by whimzyLive** [comment]
Sorry, I'm not sure what you are asking...

**Reply by playitcool** [reply]
A schema for single table. Do you have one?

**Reply by sbolanosQB** [reply]
read the docs bro :)

**Reply by playitcool** [reply]
Which doc broski?

**Reply by whimzyLive** [reply]
they are In here https://github.com/typedorm/typedorm/tree/main/docs

**Reply by bruceharrison1984** [reply]
I think he was looking for a CloudFormation template to deploy the DynamoDB table. I'm starting with TypedORM and I agree that a ready-made CF template snippet as a starting point would be helpful. I'm having to take your docs schema, and transpose it on to CloudFormation and hope that I get the indexes right.

**Reply by bruceharrison1984** [reply]
If anyone else comes looking, this should get you started.

```yaml
TypedOrm:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    TableName: TypedOrm
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      - AttributeName: gsi1_pk
        AttributeType: S
      - AttributeName: gsi1_sk
        AttributeType: S
      - AttributeName: lsi1_sk
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: gsi1
        Projection:
          ProjectionType: ALL
        KeySchema:
          - AttributeName: gsi1_pk
            KeyType: HASH
          - AttributeName: gsi1_sk
            KeyType: RANGE
    LocalSecondaryIndexes:
      - IndexName: lsi1
        Projection:
          ProjectionType: KEYS_ONLY
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: lsi1_sk
            KeyType: RANGE
```
